name: ci / pr

on:

  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:

  # Validate PR conventions.
  conventions:
    uses: firebolt-analytics/workflows/validate_conventional_pr.yaml
