name: ci / push

on:
  push:

jobs:

  # ----------------------------- #
  # SemVer & changelog generation #
  # ----------------------------- #

  version:
    runs-on: ubuntu-latest
    if:
      contains('
      refs/heads/main
      refs/heads/master
      refs/heads/staging
      refs/heads/release
      ', github.ref)
    outputs:
      new_release_published: ${{ steps.semantic_release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_release.outputs.new_release_version }}
      new_release_channel: ${{ steps.semantic_release.outputs.new_release_channel }}
      new_release_notes: ${{ steps.semantic_release.outputs.new_release_notes }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          # NOTE! Replace <VARIANT> below.
          extra_plugins: |
            @firebolt-analytics/semantic-release-config-<VARIANT>
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
