name: ci / release

on:
  release:
    types:
      - published

jobs:

  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - brs
          - simple
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update version in package.json
        run: |
          cd ./${{ matrix.config }}
          npm version ${{ github.event.release.tag_name }}

      - name: Parse SemVer
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.event.release.tag_name }}

      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ./${{ matrix.config }}/package.json
          tag: v${{ steps.semver_parser.outputs.major }}
          access: public
